/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * X10Panel.java
 *
 * Created on 13.jan.2012, 03:37:42
 */

package net.leiligheta.gui.x10;

import java.awt.event.ItemEvent;

import net.leiligheta.network.ClientMasterInterface;
import net.leiligheta.x10.X10Type;

/**
 * 
 * @author oddvar
 */
public abstract class X10Panel extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected String houseCode;
	protected int deviceCode;
	protected X10Type type;

	protected ClientMasterInterface master;

	protected boolean buttonUpdate = false;

	public void setOn(boolean on) {
		buttonUpdate = true;
		jToggleButton1.setSelected(on);
		if (type == X10Type.LAMP || type == X10Type.LAMP_NO_DIMMING) {
			if (on) {
				jToggleButton1
				.setIcon(new javax.swing.ImageIcon(
						getClass()
						.getResource(
								"/res/img/lightbulb_on-50x50.png")));
			} else {
				jToggleButton1
				.setIcon(new javax.swing.ImageIcon(
						getClass()
						.getResource(
								"/res/img/lightbulb_off-50x50.png")));
			}
		}
		buttonUpdate = false;
	}

	public X10Panel(String houseCode, int deviceCode, String description,
			X10Type type, boolean deviceOn, ClientMasterInterface master) {
		initComponents();
		this.houseCode = houseCode;
		this.deviceCode = deviceCode;
		this.type = type;
		setOn(deviceOn);
		this.master = master;
		jLabel1.setText(description);
	}

	public String getHouseCode() {
		return houseCode;
	}

	public int getDeviceCode() {
		return deviceCode;
	}

	/** Creates new form X10Panel */
	public X10Panel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jToggleButton1 = new javax.swing.JToggleButton();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();

		setBorder(javax.swing.BorderFactory.createEtchedBorder());
		setMaximumSize(new java.awt.Dimension(2147483647, 60));
		setMinimumSize(new java.awt.Dimension(165, 60));
		setPreferredSize(new java.awt.Dimension(300, 40));
		setLayout(new java.awt.BorderLayout());

		jToggleButton1.setMaximumSize(new java.awt.Dimension(50, 9));
		jToggleButton1.setMinimumSize(new java.awt.Dimension(50, 9));
		jToggleButton1.setPreferredSize(new java.awt.Dimension(50, 9));
		jToggleButton1.addItemListener(new java.awt.event.ItemListener() {
			@Override
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jToggleButton1ItemStateChanged(evt);
			}
		});
		add(jToggleButton1, java.awt.BorderLayout.LINE_END);

		jPanel1.setLayout(new java.awt.BorderLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel1.setText("jLabel1");
		jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
		jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

		add(jPanel1, java.awt.BorderLayout.CENTER);
	}// </editor-fold>//GEN-END:initComponents

	private void jToggleButton1ItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jToggleButton1ItemStateChanged
		if (evt.getStateChange() == ItemEvent.SELECTED && !buttonUpdate) {
			master.x10Power(houseCode + deviceCode, true, null);
		} else if (evt.getStateChange() == ItemEvent.DESELECTED
				&& !buttonUpdate) {
			master.x10Power(houseCode + deviceCode, false, null);
		}
	}// GEN-LAST:event_jToggleButton1ItemStateChanged

	// Variables declaration - do not modify//GEN-BEGIN:variables
	protected javax.swing.JLabel jLabel1;
	protected javax.swing.JPanel jPanel1;
	protected javax.swing.JToggleButton jToggleButton1;
	// End of variables declaration//GEN-END:variables

}
